name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - 'pypy-3.8'
        include:
          - os: windows-latest
            python-version: '3.10'
          - os: macos-latest
            python-version: '3.10'
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r dev_requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run proxyScraper
        run: python3 proxyScraper.py -p http
      - name: Run proxyChecker
        run: python3 proxyChecker.py -t 20 -s google.com -l output.txt
